name: CI/CD

on:
  push:
    branches: ['main', 'release']
  pull_request:
    branches: ['main', 'release']
    
env:
  LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
  LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
  LIGHTSAIL_USERNAME: ubunutu
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 해당 브런치로 체크아웃
        uses: actions/checkout@v4

      - name: node 설치
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: npm 설치
        run: npm install

      - name: typescript 설치
        run: npm install typescript

      - name: 빌드
        run: 
          sudo npm run build

      - name: AWS 인증하기
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Prod use SCP
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ env.LIGHTSAIL_HOST }}
          key: ${{ env.LIGHTSAIL_SSH_KEY }}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu/store24H-front"
          strip_components: 2
          
      - name: Transfer Deploy Script use SCP
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ env.LIGHTSAIL_HOST }}
          key: ${{ env.LIGHTSAIL_SSH_KEY }}
          source: "run.sh"
          target: "/home/ubuntu/script"

      - name: Execute Server Init Script
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ env.LIGHTSAIL_HOST }}
          key: ${{ env.LIGHTSAIL_SSH_KEY }}
          script_stop: true
          script: chmod +x /home/ubuntu/script/deploy.sh && sh /home/ubuntu/script/deploy.sh
      
