  name: CI/CD
	
  on:
    push:
      branches: [ release, main ]
    pull_request:
      branches: [ release, main]
	
  jobs:
    build:
      runs-on: ubuntu-latest
	
      steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          echo Build.
          npm run build

      - name: Set artifact
        run: echo "artifact=$ (ls ./build)" >> $GITHUB_ENV

      - name: Deploy to Lightsail
        uses: orderabbit/store24H-front@dep
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/store24H-front
            # 다음에 artifact 사용 가능
            echo $artifact
            sudo docker stop front
            sudo docker build -t tdf .
            sudo docker create --name front-container -p 80:80 tdf:latest
            sudo docker start front-container
            
            
            
            